In [1]:
import cv2
img=cv2.imread('image1.png')

for stacking images vertically por horizontally we have two function i.e. vstack(),hstack()

In [2]:
#print imaage will give us rgb matrix of image
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


We use the NumPy library to stack images because images can be represented as multidimensional arrays, and NumPy provides efficient tools for manipulating and processing these arrays. When stacking images, we treat them as arrays of pixel values, and NumPy's array operations allow us to combine these images either vertically or horizontally.

In [4]:
#import numpy library
import numpy as np
#hpstack function is used to join two images horizontally
twoimage=np.hstack((img,img)) #we gave 2*img it will stack image 2 times and if we wanna stack more times then we need to give that time

In [7]:
cv2.imshow("horizontal-stacking",twoimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#vertical stacking
twoimage=np.vstack((img,img))
cv2.imshow("horizontal-stacking",twoimage)
cv2.waitKey(0)
cv2.destroyAllWindows()